#!/usr/bin/env python3
"""data/*.json -> figures/generated/*.tex and figures/img/*: everything the
slides show that comes from the graph.

    python3 scripts/figures.py            (from presentation/)

- numbers.tex  one macro per number on a slide (\\NFrames, \\NKeptPct, ...)
- fig-*.tex    pgfplots charts and TikZ drawings, \\input by the chapters
- img/         Doge's own image and its templates, resized (Pillow if
               installed, else copied as they are)

Pure stdlib (+ optional Pillow). Re-run after scripts/extract.py and
scripts/stages.py to move the deck to another build: nothing on the slides
is typed in by hand except the facts in chapters/facts.tex.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import shutil
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
DATA = HERE / "data"
GEN = HERE / "figures" / "generated"
IMG = HERE / "figures" / "img"
AIRFLOW_DATA = Path(os.getenv("AIRFLOW_DATA", HERE.parent / "airflow" / "data"))

live = json.load(open(DATA / "live.json"))
st = json.load(open(DATA / "stages.json"))
ex = live["example"]
GEN.mkdir(parents=True, exist_ok=True)
IMG.mkdir(parents=True, exist_ok=True)


# -- helpers -------------------------------------------------------------------
def fmt(n) -> str:
    return f"{int(round(n)):,}"


def pct(a, b, digits=1) -> str:
    return f"{100 * a / b:.{digits}f}" if b else "0"


def short(n) -> str:
    n = float(n)
    if n >= 1e6:
        return f"{n / 1e6:.1f}M".replace(".0M", "M")
    if n >= 1e3:
        return f"{n / 1e3:.0f}k"
    return str(int(n))


def esc(s) -> str:
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def write(name: str, body: str) -> None:
    (GEN / name).write_text("% generated by scripts/figures.py — do not edit\n" + body, encoding="utf-8")


# -- the numbers ---------------------------------------------------------------
N: dict[str, str] = {}
disc, scr, par = st["discovery_state"], st["scrape_state"], st["parse_state"]
ent, cur, evs = st["entity_state"], st["curation_state"], st["event_state"]
tpl, rd = st["template_state"], st["template_reading"]
counts = live["build"]["counts"]
core = (live.get("metrics_core") or {}).get("replication", {})
integ = (live.get("metrics_core") or {}).get("integrity", {})
lay = live["layers"]

N.update(
    BuildId=esc(live["build_id"]), Version=live["build"]["version"] or "?",
    Published=str(live["build"]["published_at"])[:10],
    # collect
    Urls=fmt(disc["total"]), Confirmed=fmt(disc["confirmed"]), Unconfirmed=fmt(disc["unconfirmed"]),
    Doms=fmt(scr["doms_total"]), DomsOk=fmt(scr["doms_ok"]), DomsFailed=fmt(scr["doms_failed"]),
    DomsPermanent=fmt(scr["failed_permanent"]), DomsRetryable=fmt(scr["failed_retryable"]),
    RawGB=f"{live['doms_bytes']['raw'] / 1e9:.2f}", StoredGB=f"{live['doms_bytes']['stored'] / 1e9:.2f}",
    Compress=f"{live['doms_bytes']['raw'] / live['doms_bytes']['stored']:.1f}",
    AvgPageKB=fmt(scr["content_avg"] / 1000),
    PagesShort=f"{short(scr['doms_ok'])} pages",
    # read
    Entries=fmt(par["entries_total"]), Ready=fmt(par["entries_ready"]), Incomplete=fmt(par["entries_incomplete"]),
    ReadyPct=pct(par["entries_ready"], par["entries_total"]), ParseFailures=fmt(par["parse_failures"]),
    Parser=list(par["parser_versions"])[0],
    Memes=fmt(par["by_category"]["meme"]), CatEvents=fmt(par["by_category"]["event"]),
    CatSubcultures=fmt(par["by_category"]["subculture"]), CatPeople=fmt(par["by_category"]["person"]),
    CatSites=fmt(par["by_category"]["site"]), CatCultures=fmt(par["by_category"]["culture"]),
    # link
    Mentions=fmt(ent["mentions"]), FramesLinked=fmt(ent["frames_linked"]), Items=fmt(ent["distinct_items"]),
    OwnItem=fmt(ent["own_item"]), Kept=fmt(cur["kept_total"]), Dropped=fmt(cur["dropped_total"]),
    KeptPct=pct(cur["kept_total"], cur["kept_total"] + cur["dropped_total"]),
    JudgeKept=fmt(cur["kept"]["judge"]), JudgeDropped=fmt(cur["dropped"]["judge"]),
    RuleKept=fmt(cur["kept_total"] - cur["kept"]["judge"]),
    LinksShort=f"{short(cur['kept_total'])} links",
    # events
    Sections=fmt(evs["units_total"]), Events=fmt(evs["events_total"]), FramesEvents=fmt(evs["frames_covered"]),
    FramesEventsPct=pct(evs["frames_covered"], par["entries_total"]),
    EventsPerFrame=f"{evs['events_total'] / evs['frames_covered']:.1f}",
    DayPct=pct(evs["events_by_precision"]["day"], evs["events_total"], 0),
    MonthPct=pct(evs["events_by_precision"]["month"], evs["events_total"], 0),
    YearPct=pct(evs["events_by_precision"]["year"], evs["events_total"], 0),
    UndatedPct=pct(evs["events_by_precision"]["none"], evs["events_total"], 0),
    PlacePct=pct(evs["events_by_location_type"]["platform"] + evs["events_by_location_type"].get("both", 0),
                 evs["events_total"], 0),
    EventModel=esc(list(evs["models_in_use"])[0]),
    EventsShort=f"{short(evs['events_total'])} events",
    # templates
    FramesSearched=fmt(tpl["frames"]), FramesSelected=fmt(tpl["by_status"]["selected"]),
    FramesSelectedPct=pct(tpl["by_status"]["selected"], tpl["frames"], 0),
    NoResults=fmt(tpl["by_status"]["no_results"]), BelowThreshold=fmt(tpl["by_status"]["below_threshold"]),
    Candidates=fmt(tpl["seen"]), Merged=fmt(tpl["merged"]), Templates=fmt(tpl["kept"]),
    TemplateLinks=fmt(tpl["links"]), KymRef=fmt(tpl["methods"]["kym_reference"]),
    Read=fmt(rd["read"]), ReadFailed=fmt(rd["failed"]), Regions=fmt(rd["regions_total"]),
    Named=fmt(rd["regions_named"]), ImageLinks=fmt(rd["links_in_graph"]),
    Blind=fmt(rd["blind_named"]), BlindOk=fmt(rd["blind_confirmed"]),
    BlindPct=pct(rd["blind_confirmed"], rd["blind_named"], 0),
    TemplatesShort=f"{short(tpl['kept'])} templates",
    # the graph
    Nodes=fmt(counts["nodes"]), Edges=fmt(counts["edges"]), Triples=fmt(counts["triples"]),
    TriplesShort=short(counts["triples"]), RelTypes=fmt(len(counts["edges_by_type"])),
    Frames=fmt(counts["nodes_by_kind"]["frame"]),
    RmlTriples=fmt(live["build"]["validation"].get("rml_triples", 0)),
    TriplesDiff=fmt(counts["triples"] - live["build"]["validation"].get("rml_triples", 0)),
    CoreNodes=fmt(core.get("nodes", 0)), CoreEdges=fmt(core.get("edges", 0)),
    CoreTE=fmt(core.get("edges_triple_equivalent", 0)), CoreRels=fmt(core.get("rel_types", 0)),
    CoreDegree=f"{core.get('avg_degree', 0):.2f}",
    FramesRatio=f"{counts['nodes_by_kind']['frame'] / 12585:.2f}",
    # numbers
    WithWikidataPct=pct(lay["with_wikidata"], lay["frames"]), WithEventsPct=pct(lay["with_events"], lay["frames"]),
    WithTemplatePct=pct(lay["with_template"], lay["frames"]), WithAllPct=pct(lay["with_all"], lay["frames"]),
    WithNonePct=pct(lay["with_none"], lay["frames"]), WithNone=fmt(lay["with_none"]),
    SiblingPairs=fmt(live["sibling_pairs"]["pairs"]), SiblingLinked=fmt(live["sibling_pairs"]["linked_by_page"]),
    SiblingLinkedPct=pct(live["sibling_pairs"]["linked_by_page"], live["sibling_pairs"]["pairs"], 2),
    Sensitive=fmt(live["sensitive"]["sensitive_frames"]), SensitiveTwins=fmt(live["sensitive"]["with_public_twin"]),
    SeriesParents=fmt(integ.get("series_parents", 0)), Unresolved=fmt(integ.get("unresolved_series_parents", 0)),
    UnresolvedPct=f"{integ.get('unresolved_series_parent_pct', 0):.1f}",
    NoTypePct=f"{integ.get('frames_without_entry_type_pct', 0):.1f}",
    Components=fmt(integ.get("connected_components", 0)), ChainMax=fmt(integ.get("series_chain_max_depth", 0)),
    Isolated=fmt(integ.get("isolated_nodes", 0)), DuplicateEdges=fmt(integ.get("duplicate_edges", 0)),
    # the lexicon
    LexEntities=short((live.get("lexicon") or {}).get("entities", 0)),
    LexAliases=short((live.get("lexicon") or {}).get("aliases", 0)),
    DumpGB=f"{int((live.get('lexicon') or {}).get('meta', {}).get('dump_bytes', 0)) / 1e9:.0f}",
    DumpLines=short(int((live.get("lexicon") or {}).get("meta", {}).get("lines", 0))),
    LexGB=f"{(live.get('lexicon') or {}).get('bytes', 0) / 1e9:.1f}",
)
# Doge
e = ex["entry"]
N.update(
    DogeRawKB=fmt(ex["dom"]["raw_bytes"] / 1000), DogeStoredKB=fmt(ex["dom"]["stored_bytes"] / 1000),
    DogeLastmod=str(ex["discovery"]["lastmod"])[:10], DogeFetched=str(ex["dom"]["fetched_at"])[:10],
    DogeAddress=ex["url"].removeprefix("https://knowyourmeme.com/"),
    DogeSections=fmt(len(e["sections"])), DogeRefs=fmt(e["external_references"]), DogeTags=fmt(len(e["tags"])),
    DogeTypes=fmt(len(e["entry_type"])), DogeAboutKB=f"{len(e['about']) / 1000:.1f}",
    DogeLinks=fmt(sum(s["links"] for s in e["sections"])), DogeImages=fmt(sum(s["images"] for s in e["sections"])),
    DogeMentions=fmt(len(ex["entities"]["mentions"])),
    DogeKept=fmt(sum(1 for m in ex["entities"]["mentions"] if m["keep"])),
    DogeEvents=fmt(len(ex["events"])), DogeCandidates=fmt(ex["templates"]["candidates"]),
    DogeTemplates=fmt(len(ex["templates"]["selected"])),
    DogeSiblings=fmt(len(ex["kg"]["siblings"])),
    DogeEdges=fmt(sum(r["n"] for r in ex["kg"]["edges_by_type"])),
)
lines = [f"\\newcommand{{\\N{k}}}{{{v}}}" for k, v in N.items()]
write("numbers.tex", "\n".join(lines) + "\n")


# -- images ----------------------------------------------------------------------
def place_image(src: Path, name: str, max_px: int = 900) -> str | None:
    if not src.exists():
        return None
    dst = IMG / name
    try:
        from PIL import Image
        with Image.open(src) as im:
            im = im.convert("RGB")
            im.thumbnail((max_px, max_px))
            dst = dst.with_suffix(".jpg")
            im.save(dst, quality=88)
    except Exception:
        dst = dst.with_suffix(src.suffix)
        shutil.copyfile(src, dst)
    return dst.name


og = e["og_image"]
og_src = AIRFLOW_DATA / "kg" / "frame_images" / "files" / hashlib.sha1(og.encode()).hexdigest()[:2] / (
    hashlib.sha1(og.encode()).hexdigest() + os.path.splitext(og)[1])
doge_img = place_image(og_src, "doge")
tpl_imgs = {}
for t in ex["templates"]["selected"]:
    bp = t.get("blank_path") or ""
    src = AIRFLOW_DATA / Path(bp).relative_to("/opt/airflow/data") if bp.startswith("/opt/airflow/data") else Path(bp)
    tpl_imgs[t["template_id"]] = place_image(src, f"tpl-{t['template_id']}", 500)


# -- charts ------------------------------------------------------------------------
def hbars(rows: list[tuple[str, float, str]], color: str, width=".8\\linewidth", height=None,
          xmax_pad=1.28) -> str:
    """Horizontal bars, one series, value labels at the bar ends. rows: (label, value, shown)."""
    h = height or f"{max(len(rows), 2) * 0.78 + 0.4:.2f}cm"
    labels = ",".join("{" + lab + "}" for lab, _, _ in rows)
    coords = " ".join(f"({v},{{{lab}}}) [{shown}]" for lab, v, shown in rows)
    xmax = max(v for _, v, _ in rows) * xmax_pad
    return (
        "\\begin{tikzpicture}\n\\begin{axis}[gm hbar, scale only axis, width=" + width + ", height=" + h
        + ", xmax=" + f"{xmax:.0f}" + ", symbolic y coords={" + labels + "},\n"
        "  point meta=explicit symbolic, nodes near coords={\\pgfplotspointmeta}]\n"
        f"\\addplot[fill={color}] coordinates {{{coords}}};\n"
        "\\end{axis}\n\\end{tikzpicture}\n")


write("fig-collect-funnel.tex", hbars([
    ("URLs discovered", disc["total"], fmt(disc["total"])),
    ("confirmed entries", disc["confirmed"], fmt(disc["confirmed"])),
    ("pages stored", scr["doms_ok"], fmt(scr["doms_ok"])),
    ("entries parsed", par["entries_total"], fmt(par["entries_total"])),
], "gm@col@collect"))

miss = par["missing_field_counts"]
miss_names = {"region": "region", "section:spread": "Spread", "section:origin": "Origin",
              "entry_type": "entry type", "section:about": "About", "year": "year", "tags": "tags"}
write("fig-read-missing.tex", hbars([
    (miss_names.get(k, k), v, f"{fmt(v)}\\enspace({pct(v, par['entries_total'], 0)}\\%)")
    for k, v in sorted(miss.items(), key=lambda kv: -kv[1])], "gm@col@read"))

kept_names = {"tag_and_text": "a tag and the text agree", "judge": "the LLM judge", "platform": "a platform",
              "title_agrees": "the title agrees", "tag_named": "a whole tag names it",
              "title": "named by the title", "format": "a meme format", "own_item": "the meme's own item"}
drop_names = {"judge": "the LLM judge", "generic_item": "too generic", "deny_item": "deny list: item",
              "deny_class": "deny list: class"}
write("fig-link-kept.tex", hbars([(kept_names[k], v, fmt(v)) for k, v in
                                  sorted(cur["kept"].items(), key=lambda kv: -kv[1])], "gm@col@link",
                                 height="4.3cm"))
write("fig-link-dropped.tex", hbars([(drop_names[k], v, fmt(v)) for k, v in
                                     sorted(cur["dropped"].items(), key=lambda kv: -kv[1])],
                                    "gmMuted", height="2.0cm", xmax_pad=1.5))

prec = evs["events_by_precision"]
write("fig-events-precision.tex", hbars([
    ("to the day", prec["day"], f"{pct(prec['day'], evs['events_total'], 0)}\\%"),
    ("to the month", prec["month"], f"{pct(prec['month'], evs['events_total'], 0)}\\%"),
    ("to the year", prec["year"], f"{pct(prec['year'], evs['events_total'], 0)}\\%"),
    ("no date", prec["none"], f"{pct(prec['none'], evs['events_total'], 0)}\\%"),
], "gm@col@events", height="2.7cm", xmax_pad=1.25))


def years_chart(per_year: dict[int, int], color: str, first=1995, last=2026, note_from=None) -> str:
    coords = " ".join(f"({y},{per_year.get(y, 0)})" for y in range(first, last + 1))
    peak_y = max(range(first, last + 1), key=lambda y: per_year.get(y, 0))
    peak = per_year.get(peak_y, 0)
    shade = ""
    if note_from:
        shade = (f"\\fill[gmHair, opacity=.55] (axis cs:{note_from - .5},0) rectangle (axis cs:{last + .5},{peak * 1.12:.0f});\n"
                 f"\\node[font=\\tiny, text=gmInk2, anchor=north east, align=right] at (axis cs:{last + .4},{peak * 1.1:.0f}) "
                 "{KYM writes up\\\\a meme later};\n")
    return (
        "\\begin{tikzpicture}\n\\begin{axis}[gm axis, ybar, bar width=4.2pt, width=\\linewidth, height=4.6cm,\n"
        f"  xmin={first - .8}, xmax={last + .8}, ymin=0, ymax={peak * 1.14:.0f}, axis x line*=bottom, axis y line=none,\n"
        "  xtick={1995,2000,2005,2010,2015,2020,2025}, x tick label style={/pgf/number format/1000 sep={}},\n"
        "  every axis plot/.append style={draw=none}, clip=false]\n"
        + shade
        + f"\\addplot[fill={color}] coordinates {{{coords}}};\n"
        f"\\node[font=\\tiny, text=gmInk, anchor=south] at (axis cs:{peak_y},{peak}) {{{fmt(peak)}}};\n"
        "\\end{axis}\n\\end{tikzpicture}\n")


ev_year = Counter()
for r in live["events_by_year"]:
    if r["year"]:
        ev_year[r["year"]] += r["n"]
write("fig-events-years.tex", years_chart(ev_year, "gm@col@events", note_from=2023))

fr_year = Counter()
for r in live["frames_by_year_category"]:
    if r["year"]:
        fr_year[r["year"]] += r["n"]
write("fig-numbers-years.tex", years_chart(fr_year, "gm@col@numbers", note_from=2023))

regions = rd["regions_by_kind"]
write("fig-picture-regions.tex", hbars([(k, v, fmt(v)) for k, v in sorted(regions.items(), key=lambda kv: -kv[1])],
                                       "gm@col@picture", height="2.2cm"))

layer_rows = [("a Wikidata link", lay["with_wikidata"]), ("events", lay["with_events"]),
              ("an imgflip template", lay["with_template"]), ("all three", lay["with_all"]),
              ("none of them", lay["with_none"])]
write("fig-numbers-layers.tex", hbars([(lab, v, f"{pct(v, lay['frames'])}\\%") for lab, v in layer_rows],
                                      "gm@col@numbers", height="3.0cm", xmax_pad=1.2))

write("fig-numbers-items.tex", hbars([(esc(r["label"]), r["frames"], fmt(r["frames"]))
                                      for r in live["top_items_by_frames"][:10]], "kWikidata", height="5.0cm"))
write("fig-numbers-templates.tex", hbars([(esc(r["template"]), r["frames"], fmt(r["frames"]))
                                          for r in live["top_templates"][:8]], "kTemplate", height="4.3cm",
                                         xmax_pad=1.35))

KIND = {"frame": ("frames", "kFrame"), "frame_stub": ("frame stubs", "kStub"),
        "wikidata_entity": ("Wikidata items", "kWikidata"), "template": ("templates", "kTemplate"),
        "event": ("events", "kEvent"), "tag_concept": ("tags", "kConcept"),
        "entry_type_concept": ("entry types", "kConcept"), "origin_concept": ("origins", "kConcept"),
        "region_concept": ("regions", "kConcept"), "badge_concept": ("badges", "kConcept"),
        "image": ("images", "kDoc"), "external_ref": ("external pages", "kDoc")}
kinds = sorted(counts["nodes_by_kind"].items(), key=lambda kv: -kv[1])
body = ["\\begin{tikzpicture}[x=1cm, y=-.42cm]"]
vmax = kinds[0][1]
for i, (k, v) in enumerate(kinds):
    lab, col = KIND.get(k, (k, "gmMuted"))
    w = 6.2 * v / vmax
    body.append(f"\\node[anchor=east, font=\\scriptsize] at (-.15,{i}) {{{esc(lab)}}};")
    body.append(f"\\fill[{col}] (0,{i - .3}) rectangle ({max(w, .03):.3f},{i + .3});")
    body.append(f"\\node[anchor=west, font=\\tiny, text=gmInk2] at ({max(w, .03) + .08:.3f},{i}) {{{fmt(v)}}};")
body.append("\\end{tikzpicture}")
write("fig-graph-kinds.tex", "\n".join(body) + "\n")

# where memes are born, platform by platform: one small panel each, one scale
eras = ["4chan", "youtube", "tumblr", "reddit", "twitter", "tiktok"]
era_label = {"4chan": "4chan", "youtube": "YouTube", "tumblr": "Tumblr", "reddit": "Reddit",
             "twitter": "Twitter", "tiktok": "TikTok"}
oy = defaultdict(Counter)
for r in live["origin_by_year"]:
    if r["year"]:
        oy[r["year"]][r["origin"]] += r["n"]
years = list(range(2005, 2026))
ymax = max(oy[y].get(p, 0) for p in eras for y in years)
panels = []
for i, p in enumerate(eras):
    pts = " ".join(f"({y},{oy[y].get(p, 0)})" for y in years)
    peak_y = max(years, key=lambda y: oy[y].get(p, 0))
    total = sum(oy[y].get(p, 0) for y in years)
    panels.append(
        f"\\begin{{scope}}[xshift={i * 2.38:.2f}cm]\n"
        "\\begin{axis}[gm axis, width=2.75cm, height=3.0cm, scale only axis=false, at={(0,0)},\n"
        f"  xmin=2005, xmax=2025, ymin=0, ymax={ymax * 1.05:.0f}, axis x line*=bottom, axis y line=none,\n"
        "  xtick={2005,2025}, x tick label style={/pgf/number format/1000 sep={}, font=\\fontsize{4.5}{5}\\selectfont},\n"
        f"  title={{{era_label[p]}}}, title style={{font=\\scriptsize\\bfseries, yshift=-1.5mm}}]\n"
        f"\\addplot[fill=gm@col@numbers!70!gmSurface, draw=gm@col@numbers, line width=.6pt] coordinates {{{pts}}} \\closedcycle;\n"
        f"\\node[font=\\fontsize{{4.8}}{{5.5}}\\selectfont, text=gmInk2, anchor=south] at (axis cs:{peak_y},{oy[peak_y].get(p, 0)}) {{{peak_y}}};\n"
        "\\end{axis}\n"
        f"\\node[font=\\fontsize{{5}}{{6}}\\selectfont, text=gmMuted, anchor=north] at (1.17,-.42) {{{fmt(total)} memes}};\n"
        "\\end{scope}")
write("fig-numbers-origins.tex", "\\begin{tikzpicture}\n" + "\n".join(panels) + "\n\\end{tikzpicture}\n")


# -- Doge's story: the events in page order, as the graph chains them ------------------------
TL_LABEL = {
    0: "Homestar Runner\\\\says ``d-o-g-e''", 1: "/r/Ads: a photo\\\\``\\dots THIS DOGE''",
    2: "Tumblr: an audio\\\\adventure game", 3: "the blog\\\\Your Daily Doge",
    4: "YouTube: a fake\\\\Pok\\'emon battle", 5: "4chan /v/:\\\\doge threads",
    6: "Tumblr:\\\\``Polite Doge''", 7: "the blog\\\\F--k Yeah Doge", 8: "Shiba Confessions:\\\\``shibes''",
    9: "Reddit:\\\\/r/DogsIWannaHug", 10: "Cheezburger:\\\\``Schnauze''", 11: "Reddit: /r/Doge\\\\is created",
    12: "Reddit:\\\\/r/dailydoge", 13: "the blog\\\\shibe-doge", 14: "4chan /s4s/:\\\\600 replies",
    15: "YouTube's Comic\\\\Sans easter egg",
}
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def show_date(date, precision) -> str:
    if not date:
        return "no date"
    parts = str(date).split("-")
    if precision == "day" and len(parts) == 3:
        return f"{int(parts[2])} {MONTHS[int(parts[1]) - 1]} {parts[0]}"
    if precision == "month" and len(parts) >= 2:
        return f"{MONTHS[int(parts[1]) - 1]} {parts[0]}"
    return parts[0]


evs_d = ex["events"]
per_row = 8
tl = ["\\begin{tikzpicture}[x=1cm, y=1cm, ev/.style={circle, draw=gm@col@events, line width=.8pt, minimum size=3.2mm, inner sep=0pt}]"]
for i, ev in enumerate(evs_d):
    row, col = divmod(i, per_row)
    x = (col if row % 2 == 0 else per_row - 1 - col) * 1.9
    y = -row * 2.25
    fill = {"day": "fill=gm@col@events", "month": "fill=gm@col@events!55!gmSurface",
            "year": "fill=gm@col@events!25!gmSurface"}.get(ev["date_precision"], "fill=gmSurface, dashed")
    tl.append(f"\\node[ev, {fill}] (e{i}) at ({x:.2f},{y:.2f}) {{}};")
    tl.append(f"\\node[font=\\fontsize{{6}}{{7}}\\selectfont\\bfseries, text=gmInk, above=.9mm of e{i}] {{{show_date(ev['date'], ev['date_precision'])}}};")
    tl.append(f"\\node[font=\\fontsize{{5.6}}{{6.6}}\\selectfont, text=gmInk2, align=center, below=.9mm of e{i}] {{{TL_LABEL.get(i, '')}}};")
for i in range(1, len(evs_d)):
    same_row = (i // per_row) == ((i - 1) // per_row)
    if same_row:
        tl.append(f"\\draw[gm@col@events, line width=.7pt, -{{Stealth[length=1.6mm]}}] (e{i - 1}) -- (e{i});")
    else:
        tl.append(f"\\draw[gm@col@events, line width=.7pt, -{{Stealth[length=1.6mm]}}] (e{i - 1}.east) "
                  f"to[out=0, in=0, looseness=1.6] (e{i}.east);")
tl.append("\\end{tikzpicture}")
write("fig-events-doge.tex", "\n".join(tl) + "\n")


# -- Doge's templates: a grid of thumbnails ----------------------------------------------------
cells = []
for i, t in enumerate(ex["templates"]["selected"]):
    img = tpl_imgs.get(t["template_id"])
    col, row = i % 4, i // 4
    x, y = col * 3.35, -row * 3.15
    badge = "KYM's own link" if t["method"] == "kym_reference" else f"score {t['R']:.2f}"
    if img:
        cells.append(f"\\node[inner sep=0pt] (t{i}) at ({x:.2f},{y:.2f}) "
                     f"{{\\includegraphics[width=2.9cm,height=2.25cm,keepaspectratio]{{figures/img/{img}}}}};")
    else:
        cells.append(f"\\node[draw=gmBase, minimum width=2.9cm, minimum height=2.25cm] (t{i}) at ({x:.2f},{y:.2f}) {{}};")
    cells.append(f"\\node[font=\\tiny\\bfseries, text=gmInk, below=.6mm of t{i}, text width=3.1cm, align=center] "
                 f"(n{i}) {{{esc(t.get('name') or t['template_id'])}}};")
    cells.append(f"\\node[font=\\tiny, text={'gm@col@picture' if t['method'] == 'kym_reference' else 'gmInk2'}, "
                 f"below=0mm of n{i}] {{{badge}}};")
write("fig-picture-doge.tex", "\\begin{tikzpicture}\n" + "\n".join(cells) + "\n\\end{tikzpicture}\n")


# -- what the vision model saw: boxes on two templates ---------------------------------------
def boxes_figure(tid: int, width_cm: float) -> str:
    t = next(t for t in ex["templates"]["selected"] if t["template_id"] == tid)
    img = tpl_imgs.get(tid)
    linked = {}
    for lm in t["links"]:
        if lm.get("region") is not None and lm.get("in_graph"):
            linked[lm["region"]] = f"{lm['label']} ({lm['qid']})"
    out = ["\\begin{tikzpicture}",
           f"\\node[anchor=south west, inner sep=0pt] (img) at (0,0) "
           f"{{\\includegraphics[width={width_cm}cm]{{figures/img/{img}}}}};",
           "\\begin{scope}[x={(img.south east)}, y={(img.north west)}]"]
    for r in t["regions"]:
        x0_, y0_, x1_, y1_ = r["box"]
        y0f, y1f = 1 - y1_, 1 - y0_
        col = "kWikidata" if r["index"] in linked else "gmMuted"
        name = linked.get(r["index"], r["name"])
        out.append(f"\\draw[{col}, line width=1.4pt, rounded corners=1pt] ({x0_:.3f},{y0f:.3f}) rectangle ({x1_:.3f},{y1f:.3f});")
        out.append(f"\\node[anchor=north west, fill={col}, text=white, font=\\tiny\\bfseries, inner sep=1.2pt] "
                   f"at ({x0_:.3f},{y1f:.3f}) {{{esc(name)}}};")
    out += ["\\end{scope}", "\\end{tikzpicture}"]
    return "\n".join(out) + "\n"


write("fig-picture-boxes-a.tex", boxes_figure(247375501, 5.6))
write("fig-picture-boxes-b.tex", boxes_figure(299142114, 5.6))

print("numbers:", len(N), "| images:", doge_img, sum(1 for v in tpl_imgs.values() if v), "templates")


# -- graphs --------------------------------------------------------------------------------
KCOL = {"frame": "kFrame", "frame_stub": "kStub", "wikidata_entity": "kWikidata", "template": "kTemplate",
        "event": "kEvent", "tag_concept": "kConcept", "entry_type_concept": "kConcept",
        "origin_concept": "kConcept", "region_concept": "kConcept", "badge_concept": "kConcept",
        "image": "kDoc", "external_ref": "kDoc"}


def ellipse(angle_deg: float, r: float, squash: float = 0.56) -> tuple[float, float]:
    a = math.radians(angle_deg)
    return r * math.cos(a), r * math.sin(a) * squash


def spread(n: int, a0: float, a1: float) -> list[float]:
    if n == 1:
        return [(a0 + a1) / 2]
    return [a0 + (a1 - a0) * i / (n - 1) for i in range(n)]


# Doge at a glance — the KG_QUERIES "one frame as a graph" query, drawn: one region of the
# slide per kind of neighbour, so every node can carry its name.
kg = ex["kg"]
items = {}
for r in kg["wikidata"]:
    items.setdefault(r["qid"], r["label"])
tpl_items = {}
for t in ex["templates"]["selected"]:
    for lm in t["links"]:
        if lm.get("in_graph") and lm.get("qid"):
            tpl_items.setdefault(lm["qid"], lm["label"])
children = sorted({c["chain"][-2] for c in kg["descendants"] if len(c["chain"]) >= 2})
ancestors = (kg["ancestors"][0]["chain"] if kg["ancestors"] else ["Doge"])[1:]
siblings = [s["label"] for s in kg["siblings"]]
tags, types = kg["tags"], kg["entry_types"]

g = ["\\begin{tikzpicture}[x=1cm, y=1cm,",
     " dot/.style={circle, inner sep=0pt, minimum size=#1},",
     " lab/.style={font=\\fontsize{5.6}{6.4}\\selectfont, text=gmInk, inner sep=.7pt},",
     " edge/.style={draw=gmBase, line width=.35pt}]"]
nodes_out: list[str] = []
edges_out: list[str] = []
FLIP = {"west": "east", "east": "west", "south": "north", "north": "south"}


def put(name: str, x: float, y: float, kind: str, size: str = "2.2mm", label: str | None = None,
        anchor: str = "west") -> None:
    nodes_out.append(f"\\node[dot={size}, fill={KCOL[kind]}] ({name}) at ({x:.2f},{y:.2f}) {{}};")
    if label:
        nodes_out.append(f"\\node[lab, anchor={anchor}] at ({name}.{FLIP[anchor]}) {{{esc(label)}}};")


def column(n: int, top: float, bottom: float) -> list[float]:
    return [top] if n == 1 else [top - (top - bottom) * i / (n - 1) for i in range(n)]


put("doge", 0, 0, "frame", "8mm")
nodes_out.append("\\node[font=\\scriptsize\\bfseries, text=white] at (doge) {Doge};")
# up: the series it belongs to
prev = "doge"
for i, name in enumerate(ancestors):
    put(f"anc{i}", 0.0, 1.0 + 0.62 * i, "frame", "3.2mm", label=name, anchor="west")
    edges_out.append(f"\\draw[edge, draw=kFrame!60!gmSurface, line width=.7pt, -{{Stealth[length=1.5mm]}}] ({prev}) -- (anc{i});")
    prev = f"anc{i}"
# upper left: its children; left: its siblings
for i, (name, y) in enumerate(zip(children, column(len(children), 2.6, 1.3))):
    put(f"ch{i}", -1.7 - (i % 2) * 0.3, y, "frame", "2.8mm", label=name, anchor="east")
    edges_out.append(f"\\draw[edge, draw=kFrame!60!gmSurface, -{{Stealth[length=1.4mm]}}] (ch{i}) -- (doge);")
for i, (name, y) in enumerate(zip(siblings, column(len(siblings), 1.0, -1.25))):
    put(f"sb{i}", -5.1 - (i % 2) * 0.3, y, "frame", "2.3mm", label=name, anchor="east")
    edges_out.append(f"\\draw[edge, dashed, draw=kFrame!45!gmSurface] (doge) -- (sb{i});")
# right: the Wikidata items its text names, in two columns
half = (len(items) + 1) // 2
for i, (qid, label) in enumerate(items.items()):
    col, row = divmod(i, half)
    ys = column(half, 2.55, -0.25)
    put(f"wd{qid}", 2.6 + col * 1.95, ys[row], "wikidata_entity", label=label)
    edges_out.append(f"\\draw[edge] (doge) -- (wd{qid});")
# lower right: its templates, and what their images show
tsel = ex["templates"]["selected"]
for i, (t, y) in enumerate(zip(tsel, column(len(tsel), -0.9, -2.85))):
    put(f"t{i}", 2.2 + (i % 2) * 0.4, y, "template", "2.7mm", label=t.get("name"))
    edges_out.append(f"\\draw[edge] (doge) -- (t{i});")
extra = [q for q in tpl_items if q not in items]
for i, (qid, y) in enumerate(zip(extra, column(len(extra), -1.2, -2.6))):
    put(f"wd{qid}", 6.6, y, "wikidata_entity", label=tpl_items[qid])
for i, t in enumerate(tsel):
    for lm in t["links"]:
        if lm.get("in_graph") and lm.get("qid"):
            edges_out.append(f"\\draw[edge, draw=kTemplate!55!gmSurface] (t{i}) -- (wd{lm['qid']});")
# lower left: what kind of thing it is (entry types, tags)
for i, (name, y) in enumerate(zip(types, column(len(types), -1.55, -2.6))):
    put(f"ty{i}", -1.6, y, "entry_type_concept", "2.5mm", label=name, anchor="east")
    edges_out.append(f"\\draw[edge, draw=kConcept!40!gmSurface] (doge) -- (ty{i});")
for i, name in enumerate(tags):
    col, row = divmod(i, 4)
    put(f"tg{i}", -3.6 - col * 0.42, -1.55 - row * 0.36, "tag_concept", "1.6mm")
    edges_out.append(f"\\draw[edge, draw=kConcept!25!gmSurface, line width=.25pt] (doge) -- (tg{i});")
nodes_out.append(f"\\node[lab, text=gmInk2, anchor=north] at (-4.65,-2.95) {{{len(tags)} tags}};")
# below: the story, chained in page order
evn = len(ex["events"])
for i in range(evn):
    x = -1.05 + i * 2.1 / max(evn - 1, 1)
    put(f"ev{i}", x, -2.3 - 0.18 * math.sin(i * math.pi / max(evn - 1, 1)), "event", "2.0mm")
    edges_out.append(f"\\draw[edge, draw=kEvent!40!gmSurface, line width=.3pt] (doge) -- (ev{i});")
    if i:
        edges_out.append(f"\\draw[draw=kEvent, line width=.5pt, -{{Stealth[length=1mm]}}] (ev{i - 1}) -- (ev{i});")
nodes_out.append(f"\\node[lab, text=gmInk2, anchor=north] at (0,-2.62) {{{evn} events, one story}};")
write("fig-graph-doge.tex", "\n".join(g + nodes_out + ["\\begin{pgfonlayer}{background}"] + edges_out
                                      + ["\\end{pgfonlayer}", "\\end{tikzpicture}"]) + "\n")
legend = [("frames", "kFrame"), ("Wikidata items", "kWikidata"), ("templates", "kTemplate"),
          ("events", "kEvent"), ("types and tags", "kConcept")]
write("fig-graph-legend.tex", "\\begin{tikzpicture}[x=1cm]\n" + "\n".join(
    f"\\fill[{col}] ({i * 2.1:.2f},0) circle (.75mm); \\node[anchor=west, font=\\scriptsize, text=gmInk2] at ({i * 2.1 + .1:.2f},0) {{{lab}}};"
    for i, (lab, col) in enumerate(legend)) + "\n\\end{tikzpicture}\n")


# Everything Doge touches: one dot per edge, grouped by kind — its size, not its names.
groups = defaultdict(int)
for r in kg["edges_by_type"]:
    groups[r["kind"]] += r["n"]
order = sorted(groups.items(), key=lambda kv: -kv[1])
total = sum(groups.values())
ring = [k for k, n in order for _ in range(n)]
fl = ["\\begin{tikzpicture}[x=1cm, y=1cm]"]
pts = []
for i, kind in enumerate(ring):
    a = 90 - 360 * i / len(ring)
    r = 2.35 + 0.32 * (i % 3)
    x, y = ellipse(a, r, 0.78)
    pts.append((x, y, kind))
for x, y, kind in pts:
    fl.append(f"\\draw[gmBase!60!gmSurface, line width=.15pt] (0,0) -- ({x:.2f},{y:.2f});")
for x, y, kind in pts:
    fl.append(f"\\fill[{KCOL.get(kind, 'gmMuted')}] ({x:.2f},{y:.2f}) circle (.05);")
fl.append("\\fill[kFrame] (0,0) circle (.38); \\node[font=\\scriptsize\\bfseries, text=white] at (0,0) {Doge};")
names = {"external_ref": "external pages", "image": "images", "tag_concept": "tags", "frame": "frames",
         "event": "events", "wikidata_entity": "Wikidata items", "template": "templates",
         "entry_type_concept": "entry types", "frame_stub": "frame stubs", "origin_concept": "origin",
         "region_concept": "region", "badge_concept": "badges"}
for j, (kind, n) in enumerate(order):
    fl.append(f"\\fill[{KCOL.get(kind, 'gmMuted')}] (4.0,{1.9 - j * 0.34:.2f}) circle (.07);"
              f"\\node[anchor=west, font=\\scriptsize, text=gmInk] at (4.12,{1.9 - j * 0.34:.2f}) "
              f"{{{n}~{names.get(kind, kind)}}};")
fl.append(f"\\node[anchor=west, font=\\scriptsize\\bfseries, text=gmInk] at (3.9,2.35) {{{fmt(total)} edges}};")
fl.append("\\end{tikzpicture}")
write("fig-graph-doge-all.tex", "\n".join(fl) + "\n")

# Doge's family: its ancestors and every series that hangs under it, left to right.
parent_of = {}
for c in kg["descendants"]:
    ch = c["chain"]
    for a_, b_ in zip(ch, ch[1:]):
        parent_of[a_] = b_
chain_up = ["Doge"] + ancestors
for a_, b_ in zip(chain_up, chain_up[1:]):
    parent_of[a_] = b_
kids = defaultdict(list)
for c_, p_ in parent_of.items():
    if c_ != p_:
        kids[p_].append(c_)
root = chain_up[-1]
depth, ypos = {}, {}
leaf_y = [0.0]


def lay_out(n: str, d: int) -> float:
    depth[n] = d
    ch = sorted(set(kids.get(n, [])))
    if not ch:
        ypos[n] = leaf_y[0]
        leaf_y[0] -= 0.66
        return ypos[n]
    ys = [lay_out(c_, d + 1) for c_ in ch]
    ypos[n] = sum(ys) / len(ys)
    return ypos[n]


lay_out(root, 0)


def _hid(name: str) -> str:
    return hashlib.md5(name.encode()).hexdigest()[:10]


ft = ["\\begin{tikzpicture}[x=2.75cm, y=1cm, fam/.style={rounded corners=1.2mm, inner xsep=1.4mm, inner ysep=.9mm,"
      " font=\\fontsize{6.2}{7}\\selectfont, text width=2.45cm, align=center}]"]
for n_, d_ in depth.items():
    style = ("fill=kFrame, text=white, font=\\scriptsize\\bfseries" if n_ == "Doge"
             else "fill=kFrame!14!gmSurface, draw=kFrame!45!gmSurface" if n_ in chain_up
             else "fill=gmSurface, draw=kFrame!45!gmSurface")
    ft.append(f"\\node[fam, {style}] (n{_hid(n_)}) at ({d_},{ypos[n_]:.2f}) {{{esc(n_)}}};")
for c_, p_ in parent_of.items():
    if c_ in depth and p_ in depth:
        ft.append(f"\\draw[kFrame!50!gmSurface, line width=.5pt, -{{Stealth[length=1.3mm]}}] "
                  f"(n{_hid(c_)}.west) -- (n{_hid(p_)}.east);")
ft.append("\\end{tikzpicture}")
write("fig-numbers-family.tex", "\n".join(ft) + "\n")

# The graph of the graph: every kind of node, every kind of edge, sized by count.
POS = {"frame": (5.2, 3.0), "event": (9.9, 3.0), "external_ref": (13.2, 5.6), "image": (13.2, 0.4),
       "wikidata_entity": (1.9, 5.7), "template": (5.6, -0.2), "frame_stub": (7.6, 6.1),
       "tag_concept": (0.5, 3.0), "entry_type_concept": (1.2, 1.2), "origin_concept": (2.9, 0.1),
       "region_concept": (0.9, 4.75), "badge_concept": (3.0, 4.95)}
NAME = {"frame": "frame", "event": "event", "external_ref": "external page", "image": "image",
        "wikidata_entity": "Wikidata item", "template": "template", "frame_stub": "frame stub",
        "tag_concept": "tag", "entry_type_concept": "entry type", "origin_concept": "origin",
        "region_concept": "region", "badge_concept": "badge"}
nk = counts["nodes_by_kind"]
nmax = max(nk.values())
mg = ["\\begin{tikzpicture}[x=1cm, y=1cm]"]
BEND = {("template", "external_ref"): "bend right=28", ("event", "frame_stub"): "bend right=18",
        ("template", "image"): "bend right=8", ("frame", "external_ref"): "bend left=18",
        ("event", "frame"): "bend left=16", ("template", "wikidata_entity"): "bend left=22"}
loop_labels = defaultdict(list)
for r in sorted(live["metagraph"], key=lambda r: -r["n"]):
    s_, t_, n = r["src"], r["dst"], r["n"]
    w = 0.25 + 0.55 * max(0.0, math.log10(n / 50))
    lab = (f"node[font=\\fontsize{{4.8}}{{5.4}}\\selectfont, text=gmInk2, fill=gmSurface, inner sep=.6pt, pos=.5] "
           f"{{{r['rel']} {short(n)}}}" if n >= 25000 and s_ != t_ else "")
    if s_ == t_:
        x, y = POS[s_]
        rr = 0.18 + 0.95 * math.sqrt(nk[s_] / nmax)
        k = len(loop_labels[s_])
        mg.append(f"\\draw[gmBase, line width={w:.2f}pt] ({x - .2 - k * .1:.2f},{y + rr - .05:.2f}) "
                  f"to[out={120 + k * 12},in={60 - k * 12},looseness={8 + k * 4}] ({x + .2 + k * .1:.2f},{y + rr - .05:.2f});")
        if n >= 10000:
            loop_labels[s_].append(f"{r['rel']} {short(n)}")
        continue
    bend = BEND.get((s_, t_), "")
    arrow = f"-{{Stealth[length={1.2 + w * .6:.1f}mm]}}"
    if bend:
        mg.append(f"\\draw[gmBase, line width={w:.2f}pt, {arrow}] (k-{s_}) to[{bend}] {lab} (k-{t_});")
    else:
        mg.append(f"\\draw[gmBase, line width={w:.2f}pt, {arrow}] (k-{s_}) -- {lab} (k-{t_});")
for kind, labs in loop_labels.items():
    x, y = POS[kind]
    rr = 0.18 + 0.95 * math.sqrt(nk[kind] / nmax)
    joined = "\\\\".join(labs)
    mg.append(f"\\node[font=\\fontsize{{4.8}}{{5.6}}\\selectfont, text=gmInk2, align=center, anchor=south] "
              f"at ({x:.2f},{y + rr + 0.62 + 0.12 * len(labs):.2f}) {{{joined}}};")
nodes_mg = []
for kind, (x, y) in POS.items():
    rr = 0.18 + 0.95 * math.sqrt(nk.get(kind, 0) / nmax)
    nodes_mg.append(f"\\node[circle, fill={KCOL[kind]}, minimum size={2 * rr:.2f}cm, inner sep=0pt] (k-{kind}) at ({x},{y}) {{}};")
    nodes_mg.append(f"\\node[font=\\fontsize{{5.6}}{{6.4}}\\selectfont, text=gmInk, align=center, below=.4mm of k-{kind}] "
                    f"{{\\textbf{{{NAME[kind]}}}\\\\{fmt(nk.get(kind, 0))}}};")
# edges first would hide under the nodes; draw nodes first, then edges on the background layer
out_mg = ["\\begin{tikzpicture}[x=1cm, y=1cm]"] + nodes_mg + ["\\begin{pgfonlayer}{background}"] + mg[1:] + ["\\end{pgfonlayer}", "\\end{tikzpicture}"]
write("fig-graph-meta.tex", "\n".join(out_mg) + "\n")
print("graphs written")
