#!/usr/bin/env python3
"""data/*.json -> figures/generated/*.tex and figures/img/*: everything the
slides show that comes from the graph.

    python3 scripts/figures.py            (from presentation/)

- numbers.tex  one macro per number on a slide (\\NFrames, \\NKeptPct, ...)
- fig-*.tex    pgfplots charts and TikZ drawings, \\input by the chapters
- img/         Doge's own image and its templates, resized (Pillow if
               installed, else copied as they are)

Pure stdlib (+ optional Pillow). Re-run after scripts/extract.py and
scripts/stages.py to move the deck to another build: nothing on the slides
is typed in by hand except the facts in chapters/facts.tex.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import shutil
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
DATA = HERE / "data"
GEN = HERE / "figures" / "generated"
IMG = HERE / "figures" / "img"
AIRFLOW_DATA = Path(os.getenv("AIRFLOW_DATA", HERE.parent / "airflow" / "data"))

live = json.load(open(DATA / "live.json"))
st = json.load(open(DATA / "stages.json"))
ex = live["example"]
GEN.mkdir(parents=True, exist_ok=True)
IMG.mkdir(parents=True, exist_ok=True)


# -- helpers -------------------------------------------------------------------
def fmt(n) -> str:
    return f"{int(round(n)):,}"


def pct(a, b, digits=1) -> str:
    return f"{100 * a / b:.{digits}f}" if b else "0"


def short(n) -> str:
    n = float(n)
    if n >= 1e6:
        return f"{n / 1e6:.1f}M".replace(".0M", "M")
    if n >= 1e3:
        return f"{n / 1e3:.0f}k"
    return str(int(n))


def esc(s) -> str:
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def write(name: str, body: str) -> None:
    (GEN / name).write_text("% generated by scripts/figures.py — do not edit\n" + body, encoding="utf-8")


# -- the numbers ---------------------------------------------------------------
N: dict[str, str] = {}
disc, scr, par = st["discovery_state"], st["scrape_state"], st["parse_state"]
ent, cur, evs = st["entity_state"], st["curation_state"], st["event_state"]
tpl, rd = st["template_state"], st["template_reading"]
counts = live["build"]["counts"]
core = (live.get("metrics_core") or {}).get("replication", {})
integ = (live.get("metrics_core") or {}).get("integrity", {})
lay = live["layers"]

N.update(
    BuildId=esc(live["build_id"]), Version=live["build"]["version"] or "?",
    Published=str(live["build"]["published_at"])[:10],
    # collect
    Urls=fmt(disc["total"]), Confirmed=fmt(disc["confirmed"]), Unconfirmed=fmt(disc["unconfirmed"]),
    Doms=fmt(scr["doms_total"]), DomsOk=fmt(scr["doms_ok"]), DomsFailed=fmt(scr["doms_failed"]),
    DomsPermanent=fmt(scr["failed_permanent"]), DomsRetryable=fmt(scr["failed_retryable"]),
    RawGB=f"{live['doms_bytes']['raw'] / 1e9:.2f}", StoredGB=f"{live['doms_bytes']['stored'] / 1e9:.2f}",
    Compress=f"{live['doms_bytes']['raw'] / live['doms_bytes']['stored']:.1f}",
    AvgPageKB=fmt(scr["content_avg"] / 1000),
    PagesShort=f"{short(scr['doms_ok'])} pages",
    # read
    Entries=fmt(par["entries_total"]), Ready=fmt(par["entries_ready"]), Incomplete=fmt(par["entries_incomplete"]),
    ReadyPct=pct(par["entries_ready"], par["entries_total"]), ParseFailures=fmt(par["parse_failures"]),
    Parser=list(par["parser_versions"])[0],
    Memes=fmt(par["by_category"]["meme"]), CatEvents=fmt(par["by_category"]["event"]),
    CatSubcultures=fmt(par["by_category"]["subculture"]), CatPeople=fmt(par["by_category"]["person"]),
    CatSites=fmt(par["by_category"]["site"]), CatCultures=fmt(par["by_category"]["culture"]),
    # link
    Mentions=fmt(ent["mentions"]), FramesLinked=fmt(ent["frames_linked"]), Items=fmt(ent["distinct_items"]),
    OwnItem=fmt(ent["own_item"]), Kept=fmt(cur["kept_total"]), Dropped=fmt(cur["dropped_total"]),
    KeptPct=pct(cur["kept_total"], cur["kept_total"] + cur["dropped_total"]),
    JudgeKept=fmt(cur["kept"]["judge"]), JudgeDropped=fmt(cur["dropped"]["judge"]),
    RuleKept=fmt(cur["kept_total"] - cur["kept"]["judge"]),
    LinksShort=f"{short(cur['kept_total'])} links",
    # events
    Sections=fmt(evs["units_total"]), Events=fmt(evs["events_total"]), FramesEvents=fmt(evs["frames_covered"]),
    FramesEventsPct=pct(evs["frames_covered"], par["entries_total"]),
    EventsPerFrame=f"{evs['events_total'] / evs['frames_covered']:.1f}",
    DayPct=pct(evs["events_by_precision"]["day"], evs["events_total"], 0),
    MonthPct=pct(evs["events_by_precision"]["month"], evs["events_total"], 0),
    YearPct=pct(evs["events_by_precision"]["year"], evs["events_total"], 0),
    UndatedPct=pct(evs["events_by_precision"]["none"], evs["events_total"], 0),
    PlacePct=pct(evs["events_by_location_type"]["platform"] + evs["events_by_location_type"].get("both", 0),
                 evs["events_total"], 0),
    EventModel=esc(list(evs["models_in_use"])[0]),
    EventsShort=f"{short(evs['events_total'])} events",
    # templates
    FramesSearched=fmt(tpl["frames"]), FramesSelected=fmt(tpl["by_status"]["selected"]),
    FramesSelectedPct=pct(tpl["by_status"]["selected"], tpl["frames"], 0),
    NoResults=fmt(tpl["by_status"]["no_results"]), BelowThreshold=fmt(tpl["by_status"]["below_threshold"]),
    Candidates=fmt(tpl["seen"]), Merged=fmt(tpl["merged"]), Templates=fmt(tpl["kept"]),
    TemplateLinks=fmt(tpl["links"]), KymRef=fmt(tpl["methods"]["kym_reference"]),
    Read=fmt(rd["read"]), ReadFailed=fmt(rd["failed"]), Regions=fmt(rd["regions_total"]),
    Named=fmt(rd["regions_named"]), ImageLinks=fmt(rd["links_in_graph"]),
    Blind=fmt(rd["blind_named"]), BlindOk=fmt(rd["blind_confirmed"]),
    BlindPct=pct(rd["blind_confirmed"], rd["blind_named"], 0),
    TemplatesShort=f"{short(tpl['kept'])} templates",
    # the graph
    Nodes=fmt(counts["nodes"]), Edges=fmt(counts["edges"]), Triples=fmt(counts["triples"]),
    NodesShort=short(counts["nodes"]), EdgesShort=f"{counts['edges'] / 1e6:.2f}M",
    TriplesShort=short(counts["triples"]), RelTypes=fmt(len(counts["edges_by_type"])),
    Frames=fmt(counts["nodes_by_kind"]["frame"]),
    RmlTriples=fmt(live["build"]["validation"].get("rml_triples", 0)),
    TriplesDiff=fmt(counts["triples"] - live["build"]["validation"].get("rml_triples", 0)),
    CoreNodes=fmt(core.get("nodes", 0)), CoreEdges=fmt(core.get("edges", 0)),
    CoreTE=fmt(core.get("edges_triple_equivalent", 0)), CoreRels=fmt(core.get("rel_types", 0)),
    CoreDegree=f"{core.get('avg_degree', 0):.2f}",
    FramesRatio=f"{counts['nodes_by_kind']['frame'] / 12585:.2f}",
    # numbers
    WithWikidataPct=pct(lay["with_wikidata"], lay["frames"]), WithEventsPct=pct(lay["with_events"], lay["frames"]),
    WithTemplatePct=pct(lay["with_template"], lay["frames"]), WithAllPct=pct(lay["with_all"], lay["frames"]),
    WithNonePct=pct(lay["with_none"], lay["frames"]), WithNone=fmt(lay["with_none"]),
    SiblingPairs=fmt(live["sibling_pairs"]["pairs"]), SiblingLinked=fmt(live["sibling_pairs"]["linked_by_page"]),
    SiblingLinkedPct=pct(live["sibling_pairs"]["linked_by_page"], live["sibling_pairs"]["pairs"], 2),
    Sensitive=fmt(live["sensitive"]["sensitive_frames"]), SensitiveTwins=fmt(live["sensitive"]["with_public_twin"]),
    SeriesParents=fmt(integ.get("series_parents", 0)), Unresolved=fmt(integ.get("unresolved_series_parents", 0)),
    UnresolvedPct=f"{integ.get('unresolved_series_parent_pct', 0):.1f}",
    NoTypePct=f"{integ.get('frames_without_entry_type_pct', 0):.1f}",
    Components=fmt(integ.get("connected_components", 0)), ChainMax=fmt(integ.get("series_chain_max_depth", 0)),
    Isolated=fmt(integ.get("isolated_nodes", 0)), DuplicateEdges=fmt(integ.get("duplicate_edges", 0)),
    # the lexicon
    LexEntities=short((live.get("lexicon") or {}).get("entities", 0)),
    LexAliases=short((live.get("lexicon") or {}).get("aliases", 0)),
    DumpGB=f"{int((live.get('lexicon') or {}).get('meta', {}).get('dump_bytes', 0)) / 1e9:.0f}",
    DumpLines=short(int((live.get("lexicon") or {}).get("meta", {}).get("lines", 0))),
    LexGB=f"{(live.get('lexicon') or {}).get('bytes', 0) / 1e9:.1f}",
)
# Doge
e = ex["entry"]
N.update(
    DogeRawKB=fmt(ex["dom"]["raw_bytes"] / 1000), DogeStoredKB=fmt(ex["dom"]["stored_bytes"] / 1000),
    DogeLastmod=str(ex["discovery"]["lastmod"])[:10], DogeFetched=str(ex["dom"]["fetched_at"])[:10],
    DogeAddress=ex["url"].removeprefix("https://knowyourmeme.com/"),
    DogeSections=fmt(len(e["sections"])), DogeRefs=fmt(e["external_references"]), DogeTags=fmt(len(e["tags"])),
    DogeTypes=fmt(len(e["entry_type"])), DogeAboutKB=f"{len(e['about']) / 1000:.1f}",
    DogeLinks=fmt(sum(s["links"] for s in e["sections"])), DogeImages=fmt(sum(s["images"] for s in e["sections"])),
    DogeMentions=fmt(len(ex["entities"]["mentions"])),
    DogeKept=fmt(sum(1 for m in ex["entities"]["mentions"] if m["keep"])),
    DogeEvents=fmt(len(ex["events"])), DogeCandidates=fmt(ex["templates"]["candidates"]),
    DogeTemplates=fmt(len(ex["templates"]["selected"])),
    DogeSiblings=fmt(len(ex["kg"]["siblings"])),
    DogeEdges=fmt(sum(r["n"] for r in ex["kg"]["edges_by_type"])),
)
# curation, rule by rule (kg/curation.py's order), and the judge's roles
ck, cd_ = cur["kept"], cur["dropped"]
N.update(CurTitle=fmt(ck.get("title", 0) + ck.get("own_item", 0)), CurDenyItem=fmt(cd_.get("deny_item", 0)),
         CurPlatform=fmt(ck.get("platform", 0)), CurFormat=fmt(ck.get("format", 0)),
         CurTitleAgrees=fmt(ck.get("title_agrees", 0)), CurTagText=fmt(ck.get("tag_and_text", 0)),
         CurDenyClass=fmt(cd_.get("deny_class", 0)), CurTagNamed=fmt(ck.get("tag_named", 0)),
         CurGeneric=fmt(cd_.get("generic_item", 0)),
         CurJudged=fmt(ck.get("judge", 0) + cd_.get("judge", 0)),
         CurConfirmOverturned=fmt(cur.get("confirm_overturned", 0)),
         CurFramesJudged=fmt(cur.get("frames_judged", 0)))
roles = cur.get("judge_roles", {})
N.update({f"Role{k.title().replace('_', '')}": fmt(v) for k, v in roles.items()})
lines = [f"\\newcommand{{\\N{k}}}{{{v}}}" for k, v in N.items()]
write("numbers.tex", "\n".join(lines) + "\n")


# -- images ----------------------------------------------------------------------
def place_image(src: Path, name: str, max_px: int = 900) -> str | None:
    if not src.exists():
        return None
    dst = IMG / name
    try:
        from PIL import Image
        with Image.open(src) as im:
            im = im.convert("RGB")
            im.thumbnail((max_px, max_px))
            dst = dst.with_suffix(".jpg")
            im.save(dst, quality=88)
    except Exception:
        dst = dst.with_suffix(src.suffix)
        shutil.copyfile(src, dst)
    return dst.name


og = e["og_image"]
og_src = AIRFLOW_DATA / "kg" / "frame_images" / "files" / hashlib.sha1(og.encode()).hexdigest()[:2] / (
    hashlib.sha1(og.encode()).hexdigest() + os.path.splitext(og)[1])
doge_img = place_image(og_src, "doge")
# IMKG's own example meme (its Fig. 7): One Does Not Simply, imgflip template 61579
place_image(AIRFLOW_DATA / "templates" / "blank" / "61579.jpg", "onedoes", 700)
tpl_imgs = {}
for t in ex["templates"]["selected"]:
    bp = t.get("blank_path") or ""
    src = AIRFLOW_DATA / Path(bp).relative_to("/opt/airflow/data") if bp.startswith("/opt/airflow/data") else Path(bp)
    tpl_imgs[t["template_id"]] = place_image(src, f"tpl-{t['template_id']}", 500)


# -- charts ------------------------------------------------------------------------
def hbars(rows: list[tuple[str, float, str]], color: str, width=".8\\linewidth", height=None,
          xmax_pad=1.28) -> str:
    """Horizontal bars, one series, value labels at the bar ends. rows: (label, value, shown)."""
    h = height or f"{max(len(rows), 2) * 0.78 + 0.4:.2f}cm"
    labels = ",".join("{" + lab + "}" for lab, _, _ in rows)
    coords = " ".join(f"({v},{{{lab}}}) [{shown}]" for lab, v, shown in rows)
    xmax = max(v for _, v, _ in rows) * xmax_pad
    return (
        "\\begin{tikzpicture}\n\\begin{axis}[gm hbar, scale only axis, width=" + width + ", height=" + h
        + ", xmax=" + f"{xmax:.0f}" + ", symbolic y coords={" + labels + "},\n"
        "  point meta=explicit symbolic, nodes near coords={\\pgfplotspointmeta}]\n"
        f"\\addplot[fill={color}] coordinates {{{coords}}};\n"
        "\\end{axis}\n\\end{tikzpicture}\n")


write("fig-collect-funnel.tex", hbars([
    ("URLs discovered", disc["total"], fmt(disc["total"])),
    ("confirmed entries", disc["confirmed"], fmt(disc["confirmed"])),
    ("pages stored", scr["doms_ok"], fmt(scr["doms_ok"])),
    ("entries parsed", par["entries_total"], fmt(par["entries_total"])),
], "gm@col@collect"))

miss = par["missing_field_counts"]
miss_names = {"region": "region", "section:spread": "Spread", "section:origin": "Origin",
              "entry_type": "entry type", "section:about": "About", "year": "year", "tags": "tags"}
write("fig-read-missing.tex", hbars([
    (miss_names.get(k, k), v, f"{fmt(v)}\\enspace({pct(v, par['entries_total'], 0)}\\%)")
    for k, v in sorted(miss.items(), key=lambda kv: -kv[1])[:5]], "gm@col@read", height="2.9cm"))

kept_names = {"tag_and_text": "a tag and the text agree", "judge": "the LLM judge", "platform": "a platform",
              "title_agrees": "the title agrees", "tag_named": "a whole tag names it",
              "title": "named by the title", "format": "a meme format", "own_item": "the meme's own item"}
drop_names = {"judge": "the LLM judge", "generic_item": "too generic", "deny_item": "deny list: item",
              "deny_class": "deny list: class"}
write("fig-link-kept.tex", hbars([(kept_names[k], v, fmt(v)) for k, v in
                                  sorted(cur["kept"].items(), key=lambda kv: -kv[1])], "gm@col@link",
                                 height="4.3cm"))
write("fig-link-dropped.tex", hbars([(drop_names[k], v, fmt(v)) for k, v in
                                     sorted(cur["dropped"].items(), key=lambda kv: -kv[1])],
                                    "gmMuted", height="2.0cm", xmax_pad=1.5))

prec = evs["events_by_precision"]
write("fig-events-precision.tex", hbars([
    ("to the day", prec["day"], f"{pct(prec['day'], evs['events_total'], 0)}\\%"),
    ("to the month", prec["month"], f"{pct(prec['month'], evs['events_total'], 0)}\\%"),
    ("to the year", prec["year"], f"{pct(prec['year'], evs['events_total'], 0)}\\%"),
    ("no date", prec["none"], f"{pct(prec['none'], evs['events_total'], 0)}\\%"),
], "gm@col@events", height="2.6cm", xmax_pad=1.45, width=".72\\linewidth"))


def years_chart(per_year: dict[int, int], color: str, first=1995, last=2026, note_from=None,
                height="4.6cm") -> str:
    coords = " ".join(f"({y},{per_year.get(y, 0)})" for y in range(first, last + 1))
    peak_y = max(range(first, last + 1), key=lambda y: per_year.get(y, 0))
    peak = per_year.get(peak_y, 0)
    top = peak * 1.4            # room above the bars for the peak's number and the note
    shade = ""
    if note_from:
        shade = (f"\\fill[gmHair, opacity=.55] (axis cs:{note_from - .5},0) rectangle (axis cs:{last + .5},{top:.0f});\n"
                 f"\\node[font=\\small, text=gmInk2, anchor=north east, align=right] at (axis cs:{note_from - .7},{top * .99:.0f}) "
                 "{KYM writes up a meme later};\n")
    return (
        f"\\begin{{tikzpicture}}\n\\begin{{axis}}[gm axis, ybar, bar width=4.2pt, width=\\linewidth, height={height},\n"
        f"  xmin={first - .8}, xmax={last + .8}, ymin=0, ymax={top:.0f}, axis x line*=bottom, axis y line=none,\n"
        "  xtick={1995,2000,2005,2010,2015,2020,2025}, x tick label style={/pgf/number format/1000 sep={}},\n"
        "  every axis plot/.append style={draw=none}, clip=false]\n"
        + shade
        + f"\\addplot[fill={color}] coordinates {{{coords}}};\n"
        f"\\node[font=\\small, text=gmInk, anchor=south] at (axis cs:{peak_y},{peak}) {{{fmt(peak)}}};\n"
        "\\end{axis}\n\\end{tikzpicture}\n")


ev_year = Counter()
for r in live["events_by_year"]:
    if r["year"]:
        ev_year[r["year"]] += r["n"]
write("fig-events-years.tex", years_chart(ev_year, "gm@col@events", note_from=2023, height="5.6cm"))

fr_year = Counter()
for r in live["frames_by_year_category"]:
    if r["year"]:
        fr_year[r["year"]] += r["n"]
write("fig-numbers-years.tex", years_chart(fr_year, "gm@col@numbers", note_from=2023))

regions = rd["regions_by_kind"]
write("fig-picture-regions.tex", hbars([(k, v, fmt(v)) for k, v in sorted(regions.items(), key=lambda kv: -kv[1])],
                                       "gm@col@picture", height="2.2cm"))

layer_rows = [("a Wikidata link", lay["with_wikidata"]), ("events", lay["with_events"]),
              ("an imgflip template", lay["with_template"]), ("all three", lay["with_all"]),
              ("none of them", lay["with_none"])]
write("fig-numbers-layers.tex", hbars([(lab, v, f"{pct(v, lay['frames'])}\\%") for lab, v in layer_rows],
                                      "gm@col@numbers", height="3.0cm", xmax_pad=1.45, width=".6\\linewidth"))

write("fig-numbers-items.tex", hbars([(esc(r["label"]), r["frames"], fmt(r["frames"]))
                                      for r in live["top_items_by_frames"][:10]], "kWikidata", height="5.0cm"))
write("fig-numbers-templates.tex", hbars([(esc(r["template"]), r["frames"], fmt(r["frames"]))
                                          for r in live["top_templates"][:8]], "kTemplate", height="4.3cm",
                                         xmax_pad=1.35))

KIND = {"frame": ("frames", "kFrame"), "frame_stub": ("frame stubs", "kStub"),
        "wikidata_entity": ("Wikidata items", "kWikidata"), "template": ("templates", "kTemplate"),
        "event": ("events", "kEvent"), "tag_concept": ("tags", "kConcept"),
        "entry_type_concept": ("entry types", "kConcept"), "origin_concept": ("origins", "kConcept"),
        "region_concept": ("regions", "kConcept"), "badge_concept": ("badges", "kConcept"),
        "image": ("images", "kDoc"), "external_ref": ("external pages", "kDoc")}
kinds = sorted(counts["nodes_by_kind"].items(), key=lambda kv: -kv[1])
body = ["\\begin{tikzpicture}[x=1cm, y=-.42cm]"]
vmax = kinds[0][1]
for i, (k, v) in enumerate(kinds):
    lab, col = KIND.get(k, (k, "gmMuted"))
    w = 6.2 * v / vmax
    body.append(f"\\node[anchor=east, font=\\scriptsize] at (-.15,{i}) {{{esc(lab)}}};")
    body.append(f"\\fill[{col}] (0,{i - .3}) rectangle ({max(w, .03):.3f},{i + .3});")
    body.append(f"\\node[anchor=west, font=\\tiny, text=gmInk2] at ({max(w, .03) + .08:.3f},{i}) {{{fmt(v)}}};")
body.append("\\end{tikzpicture}")
write("fig-graph-kinds.tex", "\n".join(body) + "\n")

# where memes are born, platform by platform: one small panel each, one scale
eras = ["4chan", "youtube", "tumblr", "reddit", "twitter", "tiktok"]
era_label = {"4chan": "4chan", "youtube": "YouTube", "tumblr": "Tumblr", "reddit": "Reddit",
             "twitter": "Twitter", "tiktok": "TikTok"}
oy = defaultdict(Counter)
for r in live["origin_by_year"]:
    if r["year"]:
        oy[r["year"]][r["origin"]] += r["n"]
years = list(range(2005, 2026))
ymax = max(oy[y].get(p, 0) for p in eras for y in years)
panels = []
for i, p in enumerate(eras):
    pts = " ".join(f"({y},{oy[y].get(p, 0)})" for y in years)
    peak_y = max(years, key=lambda y: oy[y].get(p, 0))
    total = sum(oy[y].get(p, 0) for y in years)
    row, col = divmod(i, 3)
    panels.append(
        f"\\begin{{scope}}[xshift={col * 4.75:.2f}cm, yshift={-row * 3.72:.2f}cm]\n"
        "\\begin{axis}[gm axis, width=3.9cm, height=2.0cm, scale only axis, at={(0,0)},\n"
        f"  xmin=2005, xmax=2025, ymin=0, ymax={ymax * 1.3:.0f}, axis x line*=bottom, axis y line=none,\n"
        "  xtick={2005,2015,2025}, x tick label style={/pgf/number format/1000 sep={}, font=\\small},\n"
        f"  title={{{era_label[p]}}}, title style={{font=\\large\\bfseries, yshift=-1mm}}]\n"
        f"\\addplot[fill=gm@col@numbers!45!gmSurface, draw=gm@col@numbers, line width=1pt] coordinates {{{pts}}} \\closedcycle;\n"
        f"\\node[font=\\small\\bfseries, text=gmInk, anchor=south] at (axis cs:{peak_y},{oy[peak_y].get(p, 0)}) {{{peak_y}}};\n"
        "\\end{axis}\n"
        f"\\node[font=\\small, text=gmInk2, anchor=north west] at (0,-.5) {{{fmt(total)} memes}};\n"
        "\\end{scope}")
write("fig-numbers-origins.tex", "\\begin{tikzpicture}\n" + "\n".join(panels) + "\n\\end{tikzpicture}\n")


# -- Doge's story: the events in page order, as the graph chains them ------------------------
TL_LABEL = {
    0: "Homestar Runner\\\\says ``d-o-g-e''", 1: "/r/Ads: a photo\\\\``\\dots THIS DOGE''",
    2: "Tumblr: an audio\\\\adventure game", 3: "the blog\\\\Your Daily Doge",
    4: "YouTube: a fake\\\\Pok\\'emon battle", 5: "4chan /v/:\\\\doge threads",
    6: "Tumblr:\\\\``Polite Doge''", 7: "the blog\\\\F--k Yeah Doge", 8: "Shiba Confessions:\\\\``shibes''",
    9: "Reddit:\\\\/r/DogsIWannaHug", 10: "Cheezburger:\\\\``Schnauze''", 11: "Reddit: /r/Doge\\\\is created",
    12: "Reddit:\\\\/r/dailydoge", 13: "the blog\\\\shibe-doge", 14: "4chan /s4s/:\\\\600 replies",
    15: "YouTube's Comic\\\\Sans easter egg",
}
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def show_date(date, precision) -> str:
    if not date:
        return "no date"
    parts = str(date).split("-")
    if precision == "day" and len(parts) == 3:
        return f"{int(parts[2])} {MONTHS[int(parts[1]) - 1]} {parts[0]}"
    if precision == "month" and len(parts) >= 2:
        return f"{MONTHS[int(parts[1]) - 1]} {parts[0]}"
    return parts[0]


evs_d = ex["events"]
per_row = 6          # three rows: the snake reads left to right, right to left, left to right
tl = ["\\begin{tikzpicture}[x=1cm, y=1cm, ev/.style={circle, draw=gm@col@events, line width=1pt, minimum size=4.2mm, inner sep=0pt}]"]
for i, ev in enumerate(evs_d):
    row, col = divmod(i, per_row)
    x = (col if row % 2 == 0 else per_row - 1 - col) * 2.45
    y = -row * 2.05
    fill = {"day": "fill=gm@col@events", "month": "fill=gm@col@events!55!gmSurface",
            "year": "fill=gm@col@events!25!gmSurface"}.get(ev["date_precision"], "fill=gmSurface, dashed")
    tl.append(f"\\node[ev, {fill}] (e{i}) at ({x:.2f},{y:.2f}) {{}};")
    tl.append(f"\\node[font=\\fontsize{{8.5}}{{9.5}}\\selectfont\\bfseries, text=gmInk, above=1mm of e{i}] {{{show_date(ev['date'], ev['date_precision'])}}};")
    tl.append(f"\\node[font=\\fontsize{{7.6}}{{8.8}}\\selectfont, text=gmInk2, align=center, below=1mm of e{i}] {{{TL_LABEL.get(i, '')}}};")
for i in range(1, len(evs_d)):
    same_row = (i // per_row) == ((i - 1) // per_row)
    if same_row:
        tl.append(f"\\draw[gm@col@events, line width=.9pt, -{{Stealth[length=2mm]}}] (e{i - 1}) -- (e{i});")
    else:
        side = "east" if (i // per_row) % 2 == 1 else "west"
        bend = "out=0, in=0" if side == "east" else "out=180, in=180"
        tl.append(f"\\draw[gm@col@events, line width=.9pt, -{{Stealth[length=2mm]}}] (e{i - 1}.{side}) "
                  f"to[{bend}, looseness=1.5] (e{i}.{side});")
tl.append("\\end{tikzpicture}")
write("fig-events-doge.tex", "\n".join(tl) + "\n")


# -- Doge's templates: a grid of thumbnails ----------------------------------------------------
cells = []
for i, t in enumerate(ex["templates"]["selected"]):
    img = tpl_imgs.get(t["template_id"])
    col, row = i % 4, i // 4
    x, y = col * 3.35, -row * 3.15
    badge = "KYM's own link" if t["method"] == "kym_reference" else f"score {t['R']:.2f}"
    if img:
        cells.append(f"\\node[inner sep=0pt] (t{i}) at ({x:.2f},{y:.2f}) "
                     f"{{\\includegraphics[width=2.9cm,height=2.25cm,keepaspectratio]{{figures/img/{img}}}}};")
    else:
        cells.append(f"\\node[draw=gmBase, minimum width=2.9cm, minimum height=2.25cm] (t{i}) at ({x:.2f},{y:.2f}) {{}};")
    cells.append(f"\\node[font=\\tiny\\bfseries, text=gmInk, below=.6mm of t{i}, text width=3.1cm, align=center] "
                 f"(n{i}) {{{esc(t.get('name') or t['template_id'])}}};")
    cells.append(f"\\node[font=\\tiny, text={'gm@col@picture' if t['method'] == 'kym_reference' else 'gmInk2'}, "
                 f"below=0mm of n{i}] {{{badge}}};")
write("fig-picture-doge.tex", "\\begin{tikzpicture}\n" + "\n".join(cells) + "\n\\end{tikzpicture}\n")


# -- what the vision model saw: boxes on two templates ---------------------------------------
def boxes_figure(tid: int, width_cm: float) -> str:
    t = next(t for t in ex["templates"]["selected"] if t["template_id"] == tid)
    img = tpl_imgs.get(tid)
    linked = {}
    for lm in t["links"]:
        if lm.get("region") is not None and lm.get("in_graph"):
            linked[lm["region"]] = f"{lm['label']} ({lm['qid']})"
    out = ["\\begin{tikzpicture}",
           f"\\node[anchor=south west, inner sep=0pt] (img) at (0,0) "
           f"{{\\includegraphics[width={width_cm}cm]{{figures/img/{img}}}}};",
           "\\begin{scope}[x={(img.south east)}, y={(img.north west)}]"]
    for r in t["regions"]:
        x0_, y0_, x1_, y1_ = r["box"]
        y0f, y1f = 1 - y1_, 1 - y0_
        col = "kWikidata" if r["index"] in linked else "gmMuted"
        name = linked.get(r["index"], r["name"])
        out.append(f"\\draw[{col}, line width=1.4pt, rounded corners=1pt] ({x0_:.3f},{y0f:.3f}) rectangle ({x1_:.3f},{y1f:.3f});")
        out.append(f"\\node[anchor=north west, fill={col}, text=white, font=\\scriptsize\\bfseries, inner sep=1.2pt] "
                   f"at ({x0_:.3f},{y1f:.3f}) {{{esc(name)}}};")
    out += ["\\end{scope}", "\\end{tikzpicture}"]
    return "\n".join(out) + "\n"


write("fig-picture-boxes-a.tex", boxes_figure(247375501, 5.2))
write("fig-picture-boxes-b.tex", boxes_figure(299142114, 5.0))

print("numbers:", len(N), "| images:", doge_img, sum(1 for v in tpl_imgs.values() if v), "templates")


# -- graphs --------------------------------------------------------------------------------
KCOL = {"frame": "kFrame", "frame_stub": "kStub", "wikidata_entity": "kWikidata", "template": "kTemplate",
        "event": "kEvent", "tag_concept": "kConcept", "entry_type_concept": "kConcept",
        "origin_concept": "kConcept", "region_concept": "kConcept", "badge_concept": "kConcept",
        "image": "kDoc", "external_ref": "kDoc"}


def ellipse(angle_deg: float, r: float, squash: float = 0.56) -> tuple[float, float]:
    a = math.radians(angle_deg)
    return r * math.cos(a), r * math.sin(a) * squash


def spread(n: int, a0: float, a1: float) -> list[float]:
    if n == 1:
        return [(a0 + a1) / 2]
    return [a0 + (a1 - a0) * i / (n - 1) for i in range(n)]


# Doge at a glance — the KG_QUERIES "one frame as a graph" query, drawn: one region of the
# slide per kind of neighbour, so every node can carry its name.
kg = ex["kg"]
items = {}
for r in kg["wikidata"]:
    items.setdefault(r["qid"], r["label"])
tpl_items = {}
for t in ex["templates"]["selected"]:
    for lm in t["links"]:
        if lm.get("in_graph") and lm.get("qid"):
            tpl_items.setdefault(lm["qid"], lm["label"])
children = sorted({c["chain"][-2] for c in kg["descendants"] if len(c["chain"]) >= 2})
ancestors = (kg["ancestors"][0]["chain"] if kg["ancestors"] else ["Doge"])[1:]
# 7.0.0 still holds Doge twice (/memes/doge and /sensitive/memes/doge, gap 14): the twin is the
# same entry, not a sibling, and 7.1.0 holds it once — so it is not drawn as one.
siblings = [s["label"] for s in kg["siblings"] if s["label"] != "Doge"]
tags, types = kg["tags"], kg["entry_types"]

g = ["\\begin{tikzpicture}[x=1cm, y=1cm,",
     " dot/.style={circle, inner sep=0pt, minimum size=#1},",
     " lab/.style={font=\\fontsize{7.4}{8.4}\\selectfont, text=gmInk, inner sep=.8pt},",
     " edge/.style={draw=gmBase, line width=.35pt}]"]
nodes_out: list[str] = []
edges_out: list[str] = []
FLIP = {"west": "east", "east": "west", "south": "north", "north": "south"}


def put(name: str, x: float, y: float, kind: str, size: str = "2.2mm", label: str | None = None,
        anchor: str = "west") -> None:
    nodes_out.append(f"\\node[dot={size}, fill={KCOL[kind]}] ({name}) at ({x:.2f},{y:.2f}) {{}};")
    if label:
        nodes_out.append(f"\\node[lab, anchor={anchor}] at ({name}.{FLIP[anchor]}) {{{esc(label)}}};")


def column(n: int, top: float, bottom: float) -> list[float]:
    return [top] if n == 1 else [top - (top - bottom) * i / (n - 1) for i in range(n)]


put("doge", 0, 0, "frame", "8mm")
nodes_out.append("\\node[font=\\scriptsize\\bfseries, text=white] at (doge) {Doge};")
# up: the series it belongs to
prev = "doge"
for i, name in enumerate(ancestors):
    put(f"anc{i}", 0.0, 1.0 + 0.62 * i, "frame", "3.2mm", label=name, anchor="west")
    edges_out.append(f"\\draw[edge, draw=kFrame!60!gmSurface, line width=.7pt, -{{Stealth[length=1.5mm]}}] ({prev}) -- (anc{i});")
    prev = f"anc{i}"
# upper left: its children; left: its siblings
for i, (name, y) in enumerate(zip(children, column(len(children), 2.6, 1.3))):
    put(f"ch{i}", -1.7 - (i % 2) * 0.3, y, "frame", "2.8mm", label=name, anchor="east")
    edges_out.append(f"\\draw[edge, draw=kFrame!60!gmSurface, -{{Stealth[length=1.4mm]}}] (ch{i}) -- (doge);")
for i, (name, y) in enumerate(zip(siblings, column(len(siblings), 1.0, -1.25))):
    put(f"sb{i}", -5.1 - (i % 2) * 0.3, y, "frame", "2.3mm", label=name, anchor="east")
    edges_out.append(f"\\draw[edge, dashed, draw=kFrame!45!gmSurface] (doge) -- (sb{i});")
# right: the Wikidata items its text names, in two columns
half = (len(items) + 1) // 2
for i, (qid, label) in enumerate(items.items()):
    col, row = divmod(i, half)
    ys = column(half, 2.55, -0.25)
    put(f"wd{qid}", 3.8 + col * 2.05, ys[row], "wikidata_entity", label=label)
    edges_out.append(f"\\draw[edge] (doge) -- (wd{qid});")
# lower right: its templates, and what their images show
tsel = ex["templates"]["selected"]
for i, (t, y) in enumerate(zip(tsel, column(len(tsel), -0.75, -2.95))):
    put(f"t{i}", 2.45, y, "template", "2.7mm", label=t.get("name"))
    edges_out.append(f"\\draw[edge] (doge) -- (t{i});")
extra = [q for q in tpl_items if q not in items]
for i, (qid, y) in enumerate(zip(extra, column(len(extra), -1.1, -2.7))):
    put(f"wd{qid}", 6.55, y, "wikidata_entity", label=tpl_items[qid])
for i, t in enumerate(tsel):
    for lm in t["links"]:
        if lm.get("in_graph") and lm.get("qid") in extra:
            edges_out.append(f"\\draw[edge, draw=kTemplate!55!gmSurface] (t{i}) -- (wd{lm['qid']});")
# lower left: what kind of thing it is (entry types, tags)
for i, (name, y) in enumerate(zip(types, column(len(types), -1.55, -2.6))):
    put(f"ty{i}", -1.6, y, "entry_type_concept", "2.5mm", label=name, anchor="east")
    edges_out.append(f"\\draw[edge, draw=kConcept!40!gmSurface] (doge) -- (ty{i});")
for i, name in enumerate(tags):
    col, row = divmod(i, 4)
    put(f"tg{i}", -3.6 - col * 0.42, -1.55 - row * 0.36, "tag_concept", "1.6mm")
    edges_out.append(f"\\draw[edge, draw=kConcept!25!gmSurface, line width=.25pt] (doge) -- (tg{i});")
nodes_out.append(f"\\node[lab, text=gmInk2, anchor=north] at (-4.65,-2.95) {{{len(tags)} tags}};")
# below: the story, chained in page order
evn = len(ex["events"])
for i in range(evn):
    x = -1.05 + i * 2.1 / max(evn - 1, 1)
    put(f"ev{i}", x, -2.3 - 0.18 * math.sin(i * math.pi / max(evn - 1, 1)), "event", "2.0mm")
    edges_out.append(f"\\draw[edge, draw=kEvent!40!gmSurface, line width=.3pt] (doge) -- (ev{i});")
    if i:
        edges_out.append(f"\\draw[draw=kEvent, line width=.5pt, -{{Stealth[length=1mm]}}] (ev{i - 1}) -- (ev{i});")
nodes_out.append(f"\\node[lab, text=gmInk2, anchor=north] at (0,-2.62) {{{evn} events, one story}};")
write("fig-graph-doge.tex", "\n".join(g + nodes_out + ["\\begin{pgfonlayer}{background}"] + edges_out
                                      + ["\\end{pgfonlayer}", "\\end{tikzpicture}"]) + "\n")
legend = [("frames", "kFrame", 0), ("Wikidata items", "kWikidata", 2.0), ("templates", "kTemplate", 4.85),
          ("events", "kEvent", 7.2), ("types and tags", "kConcept", 9.15)]
write("fig-graph-legend.tex", "\\begin{tikzpicture}[x=1cm]\n" + "\n".join(
    f"\\fill[{col}] ({x:.2f},0) circle (1mm); \\node[anchor=west, font=\\small, text=gmInk2] at ({x + .12:.2f},0) {{{lab}}};"
    for lab, col, x in legend) + "\n\\end{tikzpicture}\n")


# Everything Doge touches: one dot per edge, grouped by kind — its size, not its names.
groups = defaultdict(int)
for r in kg["edges_by_type"]:
    groups[r["kind"]] += r["n"]
order = sorted(groups.items(), key=lambda kv: -kv[1])
total = sum(groups.values())
ring = [k for k, n in order for _ in range(n)]
fl = ["\\begin{tikzpicture}[x=1cm, y=1cm]"]
pts = []
for i, kind in enumerate(ring):
    a = 90 - 360 * i / len(ring)
    r = 2.35 + 0.32 * (i % 3)
    x, y = ellipse(a, r, 0.78)
    pts.append((x, y, kind))
for x, y, kind in pts:
    fl.append(f"\\draw[gmBase!60!gmSurface, line width=.15pt] (0,0) -- ({x:.2f},{y:.2f});")
for x, y, kind in pts:
    fl.append(f"\\fill[{KCOL.get(kind, 'gmMuted')}] ({x:.2f},{y:.2f}) circle (.05);")
fl.append("\\fill[kFrame] (0,0) circle (.38); \\node[font=\\scriptsize\\bfseries, text=white] at (0,0) {Doge};")
names = {"external_ref": "external pages", "image": "images", "tag_concept": "tags", "frame": "frames",
         "event": "events", "wikidata_entity": "Wikidata items", "template": "templates",
         "entry_type_concept": "entry types", "frame_stub": "frame stubs", "origin_concept": "origin",
         "region_concept": "region", "badge_concept": "badges"}
for j, (kind, n) in enumerate(order):
    fl.append(f"\\fill[{KCOL.get(kind, 'gmMuted')}] (4.0,{1.9 - j * 0.34:.2f}) circle (.07);"
              f"\\node[anchor=west, font=\\scriptsize, text=gmInk] at (4.12,{1.9 - j * 0.34:.2f}) "
              f"{{{n}~{names.get(kind, kind)}}};")
fl.append(f"\\node[anchor=west, font=\\scriptsize\\bfseries, text=gmInk] at (3.9,2.35) {{{fmt(total)} edges}};")
fl.append("\\end{tikzpicture}")
write("fig-graph-doge-all.tex", "\n".join(fl) + "\n")

# Doge's family: the series above it as one line, and every series that hangs under it as a
# tree, left to right — at the size it is read, not shrunk to fit.
parent_of = {}
for c in kg["descendants"]:
    ch = c["chain"]
    for a_, b_ in zip(ch, ch[1:]):
        parent_of[a_] = b_
kids = defaultdict(list)
for c_, p_ in parent_of.items():
    if c_ != p_ and c_ not in kids[p_]:
        kids[p_].append(c_)
depth, ypos = {}, {}
leaf_y = [0.0]
ROW = 0.5


def lay_out(n: str, d: int) -> float:
    depth[n] = d
    ch = sorted(kids.get(n, []), key=lambda c_: (-len(kids.get(c_, [])), c_))
    if not ch:
        ypos[n] = leaf_y[0]
        leaf_y[0] -= ROW
        return ypos[n]
    ys = [lay_out(c_, d + 1) for c_ in ch]
    ypos[n] = sum(ys) / len(ys)
    return ypos[n]


lay_out("Doge", 0)


def _hid(name: str) -> str:
    return hashlib.md5(name.encode()).hexdigest()[:10]


def short_name(n: str) -> str:
    n = n.split(" / ")[0] if len(n) > 24 else n
    if len(n) > 24:
        n = n[:22].rsplit(" ", 1)[0] + "\u2026"
    return esc(n)


ft = ["\\begin{tikzpicture}[x=3.05cm, y=1cm, fam/.style={rounded corners=1.4mm, inner xsep=1.6mm, inner ysep=1mm,"
      " font=\\fontsize{9}{10}\\selectfont, text width=2.6cm, align=center, fill=gmSurface, draw=kFrame!50!gmSurface,"
      " line width=.6pt}]"]
for n_, d_ in depth.items():
    style = "fill=kFrame, draw=kFrame, text=white, font=\\large\\bfseries, text width=1.6cm" if n_ == "Doge" else ""
    ft.append(f"\\node[fam, {style}] (n{_hid(n_)}) at ({d_},{ypos[n_]:.2f}) {{{short_name(n_)}}};")
for c_, p_ in parent_of.items():
    if c_ in depth and p_ in depth:
        ft.append(f"\\draw[kFrame!55!gmSurface, line width=.8pt, -{{Stealth[length=1.8mm]}}] "
                  f"(n{_hid(c_)}.west) -- ++(-.1,0) |- (n{_hid(p_)}.east);")
# the series above Doge, as one line over the tree
up = " \\enspace{\\color{kFrame}\\faAngleRight}\\enspace ".join(esc(a_) for a_ in reversed(ancestors))
ft.append(f"\\node[anchor=south west, font=\\normalsize, text=gmInk2] at (-.15,{max(ypos.values()) + .55:.2f}) "
          f"{{{up} \\enspace{{\\color{{kFrame}}\\faAngleRight}}\\enspace \\textbf{{\\color{{gmInk}}Doge}}}};")
ft.append("\\end{tikzpicture}")
write("fig-numbers-family.tex", "\n".join(ft) + "\n")

# The graph of the graph: every kind of node, and the arrows between two kinds, sized by count.
# Parallel arrows between the same two kinds are drawn as one, labelled in words; a kind's
# arrows to itself are written under its name. (The badge kind, one node, is left out.)
# Placed by hand so that every label has room of its own: the frame on the left with its
# arrows fanning out to the right; events in the middle, pointing on to the two biggest
# kinds (pages, images) on the far right; the vocabulary above and below the frame.
POS = {"frame": (1.6, 3.4), "event": (6.3, 3.35), "external_ref": (11.4, 5.95), "image": (11.4, 0.85),
       "template": (7.6, 0.4), "wikidata_entity": (4.2, 0.4), "frame_stub": (7.4, 6.45),
       "tag_concept": (1.9, 6.15), "region_concept": (-0.1, 6.1), "origin_concept": (1.0, 0.7),
       "entry_type_concept": (-1.0, 4.3)}
NAME = {"frame": "frame", "event": "event", "external_ref": "external page", "image": "image",
        "wikidata_entity": "Wikidata item", "template": "template", "frame_stub": "frame stub",
        "tag_concept": "tag", "entry_type_concept": "entry type", "origin_concept": "origin",
        "region_concept": "region"}
# where a kind's name goes, beside its dot
NAME_AT = {"frame": "below left", "event": "right", "tag_concept": "above", "external_ref": "above",
           "image": "below", "region_concept": "above", "frame_stub": "above"}
WORDS = {("frame", "frame"): "siblings, links", ("event", "event"): "nextInStory",
         ("tag_concept", "tag_concept"): "coOccursWith", ("origin_concept", "origin_concept"): "subTypeOf",
         ("entry_type_concept", "entry_type_concept"): "subTypeOf",
         ("frame", "wikidata_entity"): "about, tags, title", ("event", "external_ref"): "citations, embeds",
         ("frame", "frame_stub"): "citesMediaFrame", ("event", "frame"): "eventLink",
         ("event", "frame_stub"): "eventLink"}
# each arrow's label: how far along it, on which side, and whether it follows the arrow's slope
LABEL = {("frame", "external_ref"): (.75, "above", True), ("frame", "image"): (.42, "below", True),
         ("frame", "event"): (.5, "above", False), ("event", "frame"): (.5, "below", False),
         ("frame", "tag_concept"): (.5, "right", False), ("frame", "wikidata_entity"): (.55, "below", True),
         ("frame", "template"): (.55, "below", True), ("frame", "frame_stub"): (.55, "above", True),
         ("frame", "region_concept"): (.6, "left", False), ("frame", "origin_concept"): (.55, "left", False),
         ("frame", "entry_type_concept"): (.5, "above", True),
         ("event", "external_ref"): (.5, "below", True), ("event", "image"): (.72, "above", True),
         ("event", "frame_stub"): (.3, "left", False),
         ("template", "image"): (.5, "below", False), ("template", "external_ref"): (.5, "right", False),
         ("template", "wikidata_entity"): (.5, "below", False)}
BEND = {("frame", "external_ref"): "out=18, in=192"}
# the two arrows between frame and event run side by side, one lane each way
LANE = {("frame", "event"): .065, ("event", "frame"): -.065}
nk = counts["nodes_by_kind"]
nmax = max(nk.values())
pairs = defaultdict(lambda: [0, []])
for r in live["metagraph"]:
    if r["src"] in POS and r["dst"] in POS:
        pairs[(r["src"], r["dst"])][0] += r["n"]
        pairs[(r["src"], r["dst"])][1].append(r["rel"])


def radius(kind: str) -> float:
    return 0.2 + 0.92 * math.sqrt(nk.get(kind, 0) / nmax)


# labels sit on a see-through ground: the arrow under a word stays visible, the word readable
mg = ["\\begin{tikzpicture}[x=1cm, y=1cm, see through/.style={fill=gmSurface, fill opacity=.78, text opacity=1},"
      " lab/.style={font=\\fontsize{8}{9}\\selectfont, text=gmInk2, see through, inner sep=.8pt}]"]
loops = {s_: (n, WORDS.get((s_, t_), rels[0])) for (s_, t_), (n, rels) in pairs.items() if s_ == t_ and n >= 1000}
for kind, (x, y) in POS.items():
    mg.append(f"\\node[circle, fill={KCOL[kind]}, minimum size={2 * radius(kind):.2f}cm, inner sep=0pt] (k-{kind}) at ({x},{y}) {{}};")
    loop = (f"\\\\{{\\color{{gmInk2}}$\\circlearrowleft$ {loops[kind][1]} {short(loops[kind][0])}}}"
            if kind in loops else "")
    mg.append(f"\\node[font=\\fontsize{{8.5}}{{9.5}}\\selectfont, text=gmInk, align=center, see through, inner sep=.6pt,"
              f" {NAME_AT.get(kind, 'below')}=.5mm of k-{kind}] {{\\textbf{{{NAME[kind]}}} {fmt(nk.get(kind, 0))}{loop}}};")
mg.append("\\begin{pgfonlayer}{background}")
for (s_, t_), (n, rels) in sorted(pairs.items(), key=lambda kv: -kv[1][0]):
    if s_ == t_:
        continue
    w = 0.35 + 0.6 * max(0.0, math.log10(n / 50))
    words = WORDS.get((s_, t_), rels[0])
    bend = BEND.get((s_, t_), "")
    path = f"to[{bend}]" if bend else "--"
    at, side, sloped = LABEL.get((s_, t_), (.5, "above", True))
    lab = f" node[lab, {side}, {'sloped, ' if sloped else ''}pos={at}] {{{words} {short(n)}}}"
    lane = f", transform canvas={{yshift={LANE[(s_, t_)]}cm}}" if (s_, t_) in LANE else ""
    mg.append(f"\\draw[gmBase, line width={w:.2f}pt, -{{Stealth[length={1.6 + w * .5:.1f}mm]}}{lane}] "
              f"(k-{s_}) {path}{lab} (k-{t_});")
mg += ["\\end{pgfonlayer}", "\\end{tikzpicture}"]
write("fig-graph-meta.tex", "\n".join(mg) + "\n")
print("graphs written")


# -- the link chapter: how the line was drawn, how the judge was chosen ------------------------
# kg/entities.py, MIN_LINK_SCORE: 403 random frames, 25 links hand-judged per score band
# ("right item for the phrase in its sentence")
BANDS = [("0.40", 12), ("0.45", 18), ("0.50", 18), ("0.55", 22), ("0.60", 23), ("0.70+", 23)]
bd = ["\\begin{tikzpicture}[x=1cm, y=1cm]"]
for i, (lab, ok) in enumerate(BANDS):
    x = i * 1.15
    h = 2.3 * ok / 25
    col = "gmBase" if i == 0 else "gm@col@link"
    bd.append(f"\\fill[{col}, rounded corners=.6mm] ({x:.2f},0) rectangle ({x + .8:.2f},{h:.2f});")
    bd.append(f"\\node[font=\\small\\bfseries, text=gmInk, anchor=south] at ({x + .4:.2f},{h:.2f}) {{{ok}/25}};")
    bd.append(f"\\node[font=\\small, text=gmInk2, anchor=north] at ({x + .4:.2f},-.08) {{{lab}}};")
bd.append("\\draw[gmInk, line width=1.2pt, dashed] (1.03,-.1) -- (1.03,2.75) node[anchor=south, font=\\small\\bfseries, text=gmInk] {the line: 0.45};")
bd.append("\\end{tikzpicture}")
write("fig-link-bands.tex", "\n".join(bd) + "\n")

# kg/curation.py, the bake-off: kept precision and lost (relevant among dropped), per setup.
# Round 1 = 280 hand-labelled items; round 2 = 353 items, projected over the corpus.
BAKE = [("v1, mistral-small", .72, .21, 1), ("v1, ministral", .63, .14, 1), ("v1, qwen3:8b", .61, .18, 1),
        ("ministral v3", .855, .135, 2), ("ministral v4", .853, .124, 2),
        ("v4 + mistral confirming", .878, .162, 2), ("v4 + v3 confirming", .875, .126, 3)]
bk = ["\\begin{tikzpicture}",
      "\\begin{axis}[gm axis, width=7.0cm, height=5.0cm, scale only axis=false, xmin=.58, xmax=.92, ymin=.10, ymax=.23,",
      "  xlabel={relevant among kept}, ylabel={relevant among dropped}, y dir=reverse,",
      "  xtick={.6,.7,.8,.9}, ytick={.10,.15,.20}, tick label style={/pgf/number format/fixed}, clip=false]",
      "\\fill[gm@col@link!12!gmSurface] (axis cs:.85,.10) rectangle (axis cs:.92,.15);",
      "\\node[font=\\small\\bfseries, text=gm@col@link!80!gmInk, anchor=east] at (axis cs:.848,.106) {the bar};"]
for lab, x, y, rnd in BAKE:
    style = {1: "fill=gmBase", 2: "fill=gm@col@link!55!gmSurface", 3: "fill=gm@col@link"}[rnd]
    size = "2.6mm" if rnd == 3 else "1.9mm"
    bk.append(f"\\node[circle, {style}, minimum size={size}, inner sep=0pt] at (axis cs:{x},{y}) {{}};")
bk.append("\\draw[gmInk, line width=.8pt] (axis cs:.877,.127) -- (axis cs:.905,.142) node[anchor=north, font=\\small\\bfseries, text=gmInk] {chosen};")
bk.append("\\node[font=\\small, text=gmInk2, anchor=west] at (axis cs:.615,.205) {first prompts};")
bk += ["\\end{axis}", "\\end{tikzpicture}"]
write("fig-link-bakeoff.tex", "\n".join(bk) + "\n")


# -- the meaning chapter: the curated files and the census, counted ---------------------------
CFG = HERE.parent / "airflow" / "dags" / "kg_config"
M: dict[str, str] = {}
try:
    import yaml
    tx = yaml.safe_load(open(CFG / "entry_type_taxonomy.yaml", encoding="utf-8"))
    og_ = yaml.safe_load(open(CFG / "origin_taxonomy.yaml", encoding="utf-8"))
    nf = yaml.safe_load(open(CFG / "tag_normalization_exceptions.yaml", encoding="utf-8"))
    for key, name in (("broader_confirmed", "Confirmed"), ("broader_semantic_only", "SemanticOnly"),
                      ("contested", "Contested"), ("demoted", "Demoted"), ("do_not_encode_as_broader", "NotIsA"),
                      ("crosscutting_qualifiers", "Qualifiers"), ("missing_umbrellas", "Umbrellas")):
        M[f"Tax{name}"] = str(len([e for e in tx.get(key) or [] if "note" not in e or len(e) > 1]))
    M["TaxEdges"] = str(len(tx["broader_confirmed"]) + len(tx["broader_semantic_only"]))
    M["OriginAliases"] = fmt(len(og_["aliases"]))
    M["OriginConcepts"] = fmt(len(set(og_["aliases"].values())))
    M["OriginEdges"] = fmt(len(og_["broader_confirmed"]) + len(og_.get("broader_semantic_only") or []))
    M["OriginUmbrellas"] = fmt(len({e["broader"] for e in og_["broader_confirmed"]}))
    M["NoFold"] = fmt(len(nf["do_not_fold"]))
except FileNotFoundError:
    pass
etc_census = json.load(open(HERE.parent / "airflow" / "data" / "kg_census_entry_type.json"))
tag_census = json.load(open(HERE.parent / "airflow" / "data" / "kg_census_tags.json"))
tv = tag_census["value_counts"]
M.update(EntryTypes=fmt(etc_census["distinct_values"]), TypePairs=fmt(etc_census["total_pairs_returned"]),
         TagConcepts=fmt(counts["nodes_by_kind"].get("tag_concept", 0)),
         TagsRaw=fmt(tag_census["distinct_values"]),
         CoOccurs=fmt(counts["edges_by_type"].get("coOccursWith", 0)),
         SubTypeOf=fmt(counts["edges_by_type"].get("subTypeOf", 0)))
for a_, b_ in (("exploitable", "exploitables"), ("catchphrase", "catchphrases"), ("meme", "memes")):
    M[f"Fold{a_.capitalize()}"] = f"{fmt(tv.get(a_, 0))}"
    M[f"Fold{a_.capitalize()}s"] = f"{fmt(tv.get(b_, 0))}"
pairs = {(r["a"], r["b"]): r["count"] for r in tag_census["pair_cooccurrence"]}
for (a_, b_), name in ((("gaming", "video games"), "Gaming"), (("anime", "manga"), "Anime"),
                       (("donald trump", "politics"), "Trump"), (("film", "movies"), "Film"),
                       (("twitter", "x"), "TwitterX")):
    M[f"Pair{name}"] = fmt(pairs.get((a_, b_), 0))
with open(GEN / "numbers.tex", "a", encoding="utf-8") as fh:
    fh.write("% the meaning chapter\n" + "\n".join(f"\\newcommand{{\\N{k}}}{{{v}}}" for k, v in M.items()) + "\n")
print("meaning numbers:", len(M))
